### ISSUE TITLE
Cookie expires upon leaving page

### ISSUE THREAD

**Issue by Eruant** [hapijs/yar#101]
Setting a cookie, then navigating away from the initial site causes the cookie to expire.

I've set up a repo to illustrate the issue:
https://github.com/Eruant/test-hapi-yar

It contains two servers that have links to each other. On each server a cookie is set, which increments on every visit. Refreshing the page shows that the cookie is working as expected. Then following the link to the second server and back results in the first cookie being removed and created again.

The cookie has been set to last for 7 days.

**Comment by Marsup** [comment]
This is going to be hard one to fix. Cookies are bound to the domain, at some point in the RFC you could provide a port to make it port-specific, but from a quick search it doesn't seem to be supported by the browsers. So right now 2 cookies set on localhost will logically erase one another, that's expected. I don't see a way around it except if you create more aliases for the same IP so that cookies are not set on the same domain.

**Comment by Eruant** [comment]
I wasn't aware of the local host issue. However my main issue on a larger project where I need to navigate away with OAuth2, and when I come back the cookies are not set resulting in the authentication failing. In the second case I'm not using localhost.

**Comment by Eruant** [comment]
I've added a stand alone server that links to code pen, and back again. It also illustrates the issue

**Comment by Marsup** [comment]
Works for me on firefox, chrome seems to once again fail on basic things... :)

**Comment by Eruant** [comment]
Yes, same for me. I'm taking a look to see if I can see anything that might have changed in the lastest release.

**Comment by Eruant** [comment]
Looking at the headers I don't see a expiry date:
`cookie:session=Fe26.2**411e074...OOhIwkhj4wn_dI`

It appears the cookie is being treated as a session cookie. I cannot set an `Expires` segment set.

**Comment by Marsup** [comment]
That part is in the docs, look for `ttl`, it defaults to session.

**Comment by Eruant** [comment]
Yes I see. That has updated the cookie, but the issue with Chrome(ium) still remains.

**Comment by mark-bradshaw** [comment]
The problem for Chrome is the `same-site` cookie attribute.  Chrome has some particular ideas about how that should apply.  Apparently it takes an ultra purist approach and won't even share those cookies between tabs in the same window.  Sigh.

This is a newerish cookie attribute that `statehood` started supporting just 12 days ago.  See https://github.com/hapijs/statehood/commit/07a41ca2081d857964ec579a056e82c39b61545e.  When that is turned on, it sets the cookie's `same-site` attribute to `Strict`, and that's where Chrome gets picky.  So that's a new thing that's going to start causing problems for yar users apparently.

The quick fix for you is to add `isSameSite: 'Lax'` or `isSameSite: false` to your yar `cookieOptions`.  I'll probably make this a default going forward, but I want to think about it some more.  I really like the idea of same-site = Strict for security reasons, but only if Chrome is going to be reasonable about it.  Same-site = Lax is also a nice step up in security, but only protects against POST requests, not GET.  For `yar`, this is probably also problematic unless you only want session on GET requests.

**Comment by Eruant** [comment]
For now the quick fix seems to be working.

**Comment by mark-bradshaw** [comment]
I'm going to set the yar default to 'Lax' for now, and add a note to the docs.  Thanks for bringing this up.

**Comment by Eruant** [comment]
No problem, thanks for the quick responsed @Marsup and @mark-bradshaw
