### ISSUE TITLE
Deprecate?

### ISSUE THREAD

**Issue by hueniverse** [hapijs/yar#114]
This module seems to be causing more confusion than utility. If we are going to keep it, someone needs to write a nice explanation on when and how to use it (vs. cookie auth, etc). Also, if we are going to keep it, please open a hapi v17 migration issue.

**Comment by MikeBazhenov** [comment]
@hueniverse I wrote migration v17 for yar

https://github.com/hapijs/yar/pull/115

**Comment by mark-bradshaw** [comment]
Yar remains a popular session management tool.  Some people find it easier than hapi-auth-cookie, since it has more focus on a single task.  It keeps a session.  For people who want sessions without authentication, or want to store arbitrarily large amounts of data without wiring up a separate data store, yar is a much simpler path forward.

The main readme does have a small section at the bottom mentioning hapi-auth-cookie as an alternative.  If you think it would be a help I don't mind expanding that and moving it up to the top.  I definitely don't think it's good for yar to retire until hapi-auth-cookie gets split into two projects, one that manages a cookie based session and one that handles authentication.  When that happens yar will be superfluous.

**Comment by mark-bradshaw** [comment]
Closed with #115
