### ISSUE TITLE
Why is it insecure to store the session ID in the cookie directly?

### ISSUE THREAD

**Issue by alexbooker** [hapijs/yar#76]
Both [myself](https://github.com/expressjs/session/issues/176) and [some others](https://security.stackexchange.com/questions/92122/why-is-it-insecure-to-store-the-session-id-in-a-cookie-directly) are having a hard time understanding why [`express-session`](https://github.com/expressjs/session/issues/176#issuecomment-113932154) hashes the session ID cookie.

The current maintainer of `express-session` inherited the repository and while he has *some* justification as to why the library hashes the session ID, he is not certain why is predecessor did it.

 He suggested that I ask here as your library seems to do something similar.

The comments and answers on this [Information Security question](https://security.stackexchange.com/questions/92122/why-is-it-insecure-to-store-the-session-id-in-a-cookie-directly) seem to think it is unnecessary so long as your session ID is long and your random-number generation is unpredictable. Does this sound accurate to you?

I understand full well that `express-session` is not your responsibility but I am hopeful that you can help us understand why session middleware hashes/signs the cookie. What kind of attacks does it defend against?

**Comment by hueniverse** [comment]
**Disclaimer:** like any security advice from someone who doesn't know the specifics of your own system, this is for educational purposes only. Security is a complex and very specific area and if you are concerned about the security of your system you should hire an expert that can review your system along it's threat analysis and provide the appropriate advice.

First, it is nice to see all the amateur security experts who are not qualifies to offer any advice making plenty of stupid and irresponsible declarations. Signing a bearer token for internal integrity and validation is common security practice. While I don't consider what express-session is doing sufficient, it is certainly the bare minimum required.

You don't want people to be able to guess a session in order to gain access to someone else's account. No matter how random your session ID generator is, people can still try and guess sessions. Guessing a session that includes a cryptographic components is the correct way to accomplish this. It is the industry standard.

Session cookies are bearer tokens which means whoever has them can gain full access as the rightful owner. You want to be able to do a few things to reduce risk. Making sure that no one other than the server can issue valid credentials is the bare minimum and that's what is being done in express-session.

I do not consider a simple signature to be sufficient protection for session management which is why this module uses [iron](https://github.com/hueniverse/iron) encoding which both encrypts the content as well as sign it for integrity validation. This makes it practically impossible for anyone to temper with the state (as well as provides the ability to maintain some state in the cookie itself), but more importantly, it allows you to set an expiration for the credentials.

While cookies come with expiration instructions, an attacker is not required to obey. This means if someone steals a cookie, if there is no way of forcing that cookie to be short lived, it will leave the system exposed for a long time. Keeping the cookie expiration policy in sync with the server side policy is another layer of complexity and one that should not be part of the security profile of the system.

There are plenty other attack vectors here to consider. For example, if every request triggers a session storage lookup, it makes it easier to [DOS](https://en.wikipedia.org/wiki/Denial-of-service_attack) with invalid session ids. If you have a quick way of detecting that a request is coming from an attacker, you can both block it but also take measures to fight it. An invalid cookie signature can only come from a malicious source (unless you changed they way you generate cookies in which case you know that and can handle it).

Along the same lines, being able to tell when a session id is forged vs. expired is critical for maintaining a secure system. If you just generate random ids, assuming they are sufficiently long and sufficiently random, you have no way of knowing unless you keep track of every session id ever generated which would make scaling your system costly and painful. And it should be pretty obvious to tell why you want to know if an bad cookie request is coming from an attacker or not.

**Comment by Ajedi32** [comment]
@hueniverse Thanks, that's very helpful. That would make a great answer to the [original question](http://security.stackexchange.com/q/92122/29865) on Security.SE. Mind if I quote you there to give this explanation a bit more visibility? (Or perhaps you'd be interested in posting an answer there yourself?)

**Comment by Ajedi32** [comment]
@hueniverse Also, could you clarify a few things for me? There were a couple statements in that explanation that confused me:

> Guessing a session that includes a cryptographic components is the correct way to accomplish this.

What do you mean by this? Are you saying cryptographically signing the session ID makes it harder to guess? How so? How is a 128-bit random number easier to guess than a 128-bit value that represents a signed session ID?

> Making sure that no one other than the server can issue valid credentials is the bare minimum and that's what is being done in express-session.

If you're using a database of server issued session IDs to determine which IDs are valid, doesn't that already prevent anyone other than the server from issuing a valid session ID? Anyone can generate a random number, but only the server can store that value in the database to make it "valid".

**Comment by hueniverse** [comment]
@Ajedi32 Feel free to copy/paste it. The first question was a typo (bad editing) which I fixed above. It is true that having the DB issue id complies with the server-only issuing requirement but it doesn't allow for quick validation as with a crypto component. It also doesn't allow differentiation between invalid and expired.

**Comment by ircmaxell** [comment]
> You don't want people to be able to guess a session in order to gain access to someone else's account. No matter how random your session ID generator is, people can still try and guess sessions. Preventing guessing a session id by includes a cryptographic components is the correct way to accomplish this. It is the industry standard.

This is an over-statement of the situation, by a large degree. The best defense against guessing is a random id generation.

If your session id is 128 bits of cryptographically secure randomness (if it's not, stop now since you're already going to have problems), then "signing" it will simply increase the effective entropy by the hash size. If you use a 128 bit identifier, and sha-256, your effective key length will be 384 bits. However, there are still only 2^128 possible combinations. The signing doesn't add any entropy (since each identifier maps to exactly one hash). To brute force it would require brute-forcing the entire search space (384 bits).

However, brute forcing 384 bits of signed token is identical to brute forcing 384 bits of unsigned token.

And considering that even 128 bits is way beyond plausibility of brute force (if it wasn't, AES-128 would be broken), the signature adds no practical security gain.

To understand why, let's do some math. To have a 50% chance of brute-forcing a key, you need to on average exhaust half the keyspace. So a 128 bit key would have to enumerate approximately 2^127 keys. At 1,000,000,000,000 keys per second (way more than would be possible in an online attack), it'd still take 1.7*10^26 seconds (approximately 5.3 million million years). 

128 bits of random entropy is going to be well beyond brute-forcing offline for decades to come, yet alone online brute-forcing.

The FAR bigger concerns are predictable session identifiers (auto-incrementing ids, poor random quality, etc) and session hijacking (stealing the session identifiers in flight). To solve the first, use a strong random number generator. To solve the second, protect against XSS and use TLS (HTTPS).

Signing token may feels good, but it provides no security over any even remotely practical attack.

**Comment by hueniverse** [comment]
@ircmaxell again, like a few before, you are focusing on one aspect of the design and pointlessly picking at it. A good security system must include layering and relying solely on strong randomness is an incomplete solution. Even if you can prevent guessing, you won't be able to detect an attacker (vs. repeated requests for expired sessions). What makes this code hard to reason about is that it lack separation of concerns - but that doesn't mean it is not providing meaningful value.

All the fancy math above doesn't change the basic fact that the current design is the right one given the way this is actually used.

I feel like I'm repeating myself.

**Comment by ircmaxell** [comment]
@hueniverse in your use of it in this library (considering you don't control the ids), it's the lesser of evils. Yes, it does add security to poor ids. However, it's a bandaid on a gunshot wound (a better design would be to always generate a cryptographically secure random number via `crypto.randomBytes()` or the equivalent.

The reason I replied here is that you are citing the general security principles of signed session identifiers, which is incorrect. The principles you say are valid for arbitrary identifiers. But considering others are citing you and using it to suggest that random identifiers are weaker if they are unsigned (you infact yourself did this [in another thread](https://github.com/expressjs/session/issues/176#issuecomment-119451350).

I'm not saying you should remove signatures. I'm saying you should recognize that the benefit they provide is because of a design decision that other implementations don't deal with. And considering others are citing your write-up as justification for why not using signed identifiers is bad, it's a very important distinction to make.
